"""Add completed_at field to ProductionBatchItem

Revision ID: 005f0adfdd4d
Revises: 322346bd1261
Create Date: 2025-05-28 15:51:41.830442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005f0adfdd4d'
down_revision = '322346bd1261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_allocations', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_material_allocation_global_sn', ['global_sn'])

    with op.batch_alter_table('production_batch_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_production_batch_item_global_sn', ['global_sn'])

    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_production_batch_global_sn', ['global_sn'])

    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_production_order_global_sn', ['global_sn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_production_order_global_sn', type_='unique')

    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.drop_constraint('uq_production_batch_global_sn', type_='unique')

    with op.batch_alter_table('production_batch_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_production_batch_item_global_sn', type_='unique')
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('material_allocations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_material_allocation_global_sn', type_='unique')

    # ### end Alembic commands ###
