"""Add sales order management tables

Revision ID: 011e395c1aa4
Revises: 83bfde43921e
Create Date: 2025-06-04 11:29:40.112078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011e395c1aa4'
down_revision = '83bfde43921e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('delivery_quantity', sa.Integer(), nullable=False),
    sa.Column('delivery_address', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['sales_order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_delivery_schedule_global_sn'),
    sa.UniqueConstraint('order_item_id', 'batch_number', name='uq_delivery_batch')
    )
    op.drop_table('sales_order_delivery_batches')
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('spec_gasket', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('using_unit', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('order_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('delivery_notes', sa.Text(), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('direction',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('spec_extended',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('spec_joint',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('spec_drilling',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('spec_other',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.drop_column('order_time')
        batch_op.drop_column('drawing_number')
        batch_op.drop_column('usage_unit')
        batch_op.drop_column('status')
        batch_op.drop_column('delivery_time')
        batch_op.drop_column('specification_type')
        batch_op.drop_column('product_name')
        batch_op.drop_column('sequence')
        batch_op.drop_column('spec_pad')
        batch_op.drop_column('delivery_station_notes')
        batch_op.drop_column('specification_detail')
        batch_op.drop_column('unit')

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_month', sa.String(length=7), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.drop_column('order_year')
        batch_op.drop_column('order_month')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_month', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('order_year', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('year_month')

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('specification_detail', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('delivery_station_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('spec_pad', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('sequence', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('specification_type', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('delivery_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('usage_unit', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('drawing_number', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('order_time', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('spec_other',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('spec_drilling',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('spec_joint',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('spec_extended',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('direction',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('delivery_notes')
        batch_op.drop_column('order_date')
        batch_op.drop_column('using_unit')
        batch_op.drop_column('spec_gasket')
        batch_op.drop_column('unit_price')

    op.create_table('sales_order_delivery_batches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('global_sn', sa.VARCHAR(length=8), nullable=False),
    sa.Column('order_item_id', sa.INTEGER(), nullable=False),
    sa.Column('batch_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('planned_delivery_time', sa.DATETIME(), nullable=False),
    sa.Column('actual_delivery_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('tracking_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('delivery_address', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['sales_order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn', name='uq_delivery_batch_global_sn'),
    sa.UniqueConstraint('order_item_id', 'batch_number', name='uq_delivery_batch_number')
    )
    op.drop_table('delivery_schedules')
    # ### end Alembic commands ###
