"""add output_type and code_rule_id to process_price

Revision ID: 09e73de5e834
Revises: 81d69499eb59
Create Date: 2025-05-12 14:57:35.833837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e73de5e834'
down_revision = '81d69499eb59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('code_rule_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_process_code_rule_id', 'code_rule', ['code_rule_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_price', schema=None) as batch_op:
        batch_op.drop_constraint('fk_process_code_rule_id', type_='foreignkey')
        batch_op.drop_column('code_rule_id')
        batch_op.drop_column('output_type')

    # ### end Alembic commands ###
