"""Add raw material and finished product fields to production record

Revision ID: 0d68610b89b7
Revises: 1f7dc0501684
Create Date: 2025-05-12 18:35:39.409329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d68610b89b7'
down_revision = '1f7dc0501684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_record_materials')
    op.drop_table('inventory_change')
    with op.batch_alter_table('production_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_material_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('raw_material_quantity', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'raw_material', ['raw_material_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('raw_material_quantity')
        batch_op.drop_column('raw_material_id')

    op.create_table('inventory_change',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('global_sn', sa.VARCHAR(length=8), nullable=False),
    sa.Column('material_id', sa.INTEGER(), nullable=False),
    sa.Column('change_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('change_date', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['raw_material.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn', name='uq_inventory_change_global_sn')
    )
    op.create_table('production_record_materials',
    sa.Column('production_record_id', sa.INTEGER(), nullable=False),
    sa.Column('raw_material_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['production_record_id'], ['production_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('production_record_id', 'raw_material_id')
    )
    # ### end Alembic commands ###
