"""Add new fields to production record

Revision ID: 142d11630569
Revises: 09e73de5e834
Create Date: 2025-05-12 17:39:09.297652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142d11630569'
down_revision = '09e73de5e834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('raw_material_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('raw_material_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('finished_product_id', sa.Integer(), nullable=True))
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('process_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               nullable=False)
        batch_op.create_foreign_key('fk_production_record_raw_material', 'raw_material', ['raw_material_id'], ['id'])
        batch_op.create_foreign_key('fk_production_record_finished_product', 'finished_product', ['finished_product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_record', schema=None) as batch_op:
        batch_op.drop_constraint('fk_production_record_finished_product', type_='foreignkey')
        batch_op.drop_constraint('fk_production_record_raw_material', type_='foreignkey')
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('process_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('finished_product_id')
        batch_op.drop_column('raw_material_quantity')
        batch_op.drop_column('raw_material_id')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
