"""add indexes for quality management tables

Revision ID: 1d77f62a8743
Revises: c02604883c72
Create Date: 2025-05-14 14:42:35.526601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d77f62a8743'
down_revision = 'c02604883c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonus_penalty', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_bonus_penalty_global_sn', ['global_sn'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_employee_global_sn', ['global_sn'])

    with op.batch_alter_table('employee_coefficient_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_coefficient_history_global_sn', ['global_sn'])

    with op.batch_alter_table('employee_salary_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_salary_history_global_sn', ['global_sn'])

    with op.batch_alter_table('finished_product', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_finished_product_global_sn', ['global_sn'])
        batch_op.create_unique_constraint('uq_finished_product_serial_number', ['serial_number'])

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_records_global_sn'), ['global_sn'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspection_records_inspection_date'), ['inspection_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_records_inspector_id'), ['inspector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_records_result'), ['result'], unique=False)

    with op.batch_alter_table('inspection_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_tasks_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_tasks_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_tasks_global_sn'), ['global_sn'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspection_tasks_inspector_id'), ['inspector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_tasks_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_tasks_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_tasks_template_id'), ['template_id'], unique=False)

    with op.batch_alter_table('inspection_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_templates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_templates_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_templates_template_code'), ['template_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspection_templates_type'), ['type'], unique=False)

    with op.batch_alter_table('process_price', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_process_price_global_sn', ['global_sn'])

    with op.batch_alter_table('process_price_group', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_process_price_group_global_sn', ['global_sn'])

    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_raw_material_global_sn', ['global_sn'])

    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_task_assignment_global_sn', ['global_sn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_task_assignment_global_sn', type_='unique')

    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.drop_constraint('uq_raw_material_global_sn', type_='unique')

    with op.batch_alter_table('process_price_group', schema=None) as batch_op:
        batch_op.drop_constraint('uq_process_price_group_global_sn', type_='unique')

    with op.batch_alter_table('process_price', schema=None) as batch_op:
        batch_op.drop_constraint('uq_process_price_global_sn', type_='unique')

    with op.batch_alter_table('inspection_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_templates_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_templates_template_code'))
        batch_op.drop_index(batch_op.f('ix_inspection_templates_is_active'))
        batch_op.drop_index(batch_op.f('ix_inspection_templates_created_at'))

    with op.batch_alter_table('inspection_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_tasks_template_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_tasks_target_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_tasks_target_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_inspection_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_inspection_tasks_inspector_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_tasks_global_sn'))
        batch_op.drop_index(batch_op.f('ix_inspection_tasks_deadline'))
        batch_op.drop_index(batch_op.f('ix_inspection_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_inspection_tasks_completed_at'))

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_records_result'))
        batch_op.drop_index(batch_op.f('ix_inspection_records_inspector_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_records_inspection_date'))
        batch_op.drop_index(batch_op.f('ix_inspection_records_global_sn'))
        batch_op.drop_index(batch_op.f('ix_inspection_records_created_at'))

    with op.batch_alter_table('finished_product', schema=None) as batch_op:
        batch_op.drop_constraint('uq_finished_product_serial_number', type_='unique')
        batch_op.drop_constraint('uq_finished_product_global_sn', type_='unique')

    with op.batch_alter_table('employee_salary_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_salary_history_global_sn', type_='unique')

    with op.batch_alter_table('employee_coefficient_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_coefficient_history_global_sn', type_='unique')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_global_sn', type_='unique')

    with op.batch_alter_table('bonus_penalty', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bonus_penalty_global_sn', type_='unique')

    # ### end Alembic commands ###
