"""add_production_record_materials_relationship

Revision ID: 1f7dc0501684
Revises: bcb9bf714586
Create Date: 2025-05-12 18:24:35.209649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7dc0501684'
down_revision = 'bcb9bf714586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_change', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_inventory_change_global_sn', ['global_sn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_change', schema=None) as batch_op:
        batch_op.drop_constraint('uq_inventory_change_global_sn', type_='unique')

    # ### end Alembic commands ###
