"""add is_archived field to inventory models

Revision ID: 22b8de65652a
Revises: 3128866575b8
Create Date: 2025-05-27 10:07:07.993921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b8de65652a'
down_revision = '3128866575b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    with op.batch_alter_table('finished_product', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
