"""add product mbom tables

Revision ID: 29e80e4970ac
Revises: aa8736ba6969
Create Date: 2025-05-28 09:46:57.740194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e80e4970ac'
down_revision = 'aa8736ba6969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('drawing_number', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_product_global_sn'),
    sa.UniqueConstraint('product_code', name='uq_product_code')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_product_code'), ['product_code'], unique=True)

    op.create_table('product_bom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=20), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('waste_rate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_product_bom_global_sn')
    )
    with op.batch_alter_table('product_bom', schema=None) as batch_op:
        batch_op.create_index('ix_product_bom_material', ['material_type', 'material_id'], unique=False)

    op.create_table('product_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('setup_time', sa.Float(), nullable=True),
    sa.Column('process_time', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['process_price.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_product_process_global_sn'),
    sa.UniqueConstraint('product_id', 'sequence', name='uq_product_process_sequence')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_processes')
    with op.batch_alter_table('product_bom', schema=None) as batch_op:
        batch_op.drop_index('ix_product_bom_material')

    op.drop_table('product_bom')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_code'))

    op.drop_table('products')
    # ### end Alembic commands ###
