"""add_production_order_and_batch_management

Revision ID: 322346bd1261
Revises: 29e80e4970ac
Create Date: 2025-05-28 10:39:11.712560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322346bd1261'
down_revision = '29e80e4970ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('planned_quantity', sa.Integer(), nullable=False),
    sa.Column('completed_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('planned_start_date', sa.Date(), nullable=False),
    sa.Column('planned_end_date', sa.Date(), nullable=False),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_production_order_global_sn'),
    sa.UniqueConstraint('order_number', name='uq_production_order_number')
    )
    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_orders_order_number'), ['order_number'], unique=True)

    op.create_table('material_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=20), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity', sa.Float(), nullable=False),
    sa.Column('allocated_quantity', sa.Float(), nullable=True),
    sa.Column('consumed_quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_material_allocation_global_sn')
    )
    with op.batch_alter_table('material_allocations', schema=None) as batch_op:
        batch_op.create_index('ix_material_allocation_material', ['material_type', 'material_id'], unique=False)

    op.create_table('production_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('batch_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number', name='uq_production_batch_number'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_production_batch_global_sn')
    )
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_batches_batch_number'), ['batch_number'], unique=True)

    op.create_table('production_batch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('item_sequence', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.Column('inspector', sa.String(length=50), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'item_sequence', name='uq_batch_item_sequence'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_production_batch_item_global_sn'),
    sa.UniqueConstraint('product_code', name='uq_production_batch_item_code')
    )
    with op.batch_alter_table('production_batch_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_batch_items_product_code'), ['product_code'], unique=True)

    op.drop_table('_alembic_tmp_product_bom')
    with op.batch_alter_table('product_bom', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_product_bom_global_sn', ['global_sn'])

    with op.batch_alter_table('product_processes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_product_process_global_sn', ['global_sn'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_rule_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_product_global_sn', ['global_sn'])
        batch_op.create_foreign_key('fk_products_code_rule_id', 'code_rule', ['code_rule_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_code_rule_id', type_='foreignkey')
        batch_op.drop_constraint('uq_product_global_sn', type_='unique')
        batch_op.drop_column('code_rule_id')

    with op.batch_alter_table('product_processes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_process_global_sn', type_='unique')

    with op.batch_alter_table('product_bom', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_bom_global_sn', type_='unique')

    op.create_table('_alembic_tmp_product_bom',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('global_sn', sa.VARCHAR(length=8), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('material_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('material_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('unit_cost', sa.FLOAT(), nullable=True),
    sa.Column('waste_rate', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('sequence', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn', name='uq_product_bom_global_sn')
    )
    with op.batch_alter_table('production_batch_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_batch_items_product_code'))

    op.drop_table('production_batch_items')
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_batches_batch_number'))

    op.drop_table('production_batches')
    with op.batch_alter_table('material_allocations', schema=None) as batch_op:
        batch_op.drop_index('ix_material_allocation_material')

    op.drop_table('material_allocations')
    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_orders_order_number'))

    op.drop_table('production_orders')
    # ### end Alembic commands ###
