"""Remove material_name column from raw_material

Revision ID: 33c7d77643c1
Revises: c4b4caaebd94
Create Date: 2025-06-11 17:24:09.388541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '33c7d77643c1'
down_revision = 'c4b4caaebd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.drop_table('_alembic_tmp_raw_material')
    op.drop_table('_alembic_tmp_notification_rules')
    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_notification_rule_global_sn', ['global_sn'])

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_notification_template_code', ['template_code'])
        batch_op.create_unique_constraint('uq_notification_template_global_sn', ['global_sn'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_notification_global_sn', ['global_sn'])

    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sales_orders', ['sales_order_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'sales_order_items', ['sales_order_item_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'raw_material_categories', ['category_id'], ['id'])
        batch_op.drop_column('material_name')

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_column('usage_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_unit', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notification_global_sn', type_='unique')

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notification_template_global_sn', type_='unique')
        batch_op.drop_constraint('uq_notification_template_code', type_='unique')

    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notification_rule_global_sn', type_='unique')

    op.create_table('_alembic_tmp_notification_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('global_sn', sa.VARCHAR(length=8), nullable=False),
    sa.Column('rule_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('trigger_conditions', sqlite.JSON(), nullable=True),
    sa.Column('receiver_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('receiver_config', sqlite.JSON(), nullable=True),
    sa.Column('notification_methods', sqlite.JSON(), nullable=True),
    sa.Column('template_config', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn', name='uq_notification_rule_global_sn')
    )
    op.create_table('_alembic_tmp_raw_material',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('global_sn', sa.VARCHAR(length=8), nullable=False),
    sa.Column('supplier', sa.VARCHAR(length=100), nullable=False),
    sa.Column('melt_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('supplier_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('has_sample', sa.BOOLEAN(), nullable=True),
    sa.Column('storage_date', sa.DATETIME(), nullable=False),
    sa.Column('internal_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'in_stock'"), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['raw_material_categories.id'], name='fk_raw_material_category_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn', name='uq_raw_material_global_sn'),
    sa.UniqueConstraint('internal_number', name='uq_raw_material_internal_number')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
