"""Add raw material and finished product fields to production record

Revision ID: 3bcbf4400568
Revises: 0d68610b89b7
Create Date: 2025-05-12 18:40:04.260733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bcbf4400568'
down_revision = '0d68610b89b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_material_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('raw_material_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('finished_product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_production_record_raw_material', 'raw_material', ['raw_material_id'], ['id'])
        batch_op.create_foreign_key('fk_production_record_finished_product', 'finished_product', ['finished_product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_record', schema=None) as batch_op:
        batch_op.drop_constraint('fk_production_record_finished_product', type_='foreignkey')
        batch_op.drop_constraint('fk_production_record_raw_material', type_='foreignkey')
        batch_op.drop_column('finished_product_id')
        batch_op.drop_column('raw_material_quantity')
        batch_op.drop_column('raw_material_id')

    # ### end Alembic commands ###
