"""Add rollback fields to audit log

Revision ID: 54d1a1cbba35
Revises: 363d19bcbac0
Create Date: 2024-03-19 11:23:45.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d1a1cbba35'
down_revision = '363d19bcbac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_rollback', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rollback_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('old_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('new_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rolled_back', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rolled_back_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rolled_back_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_audit_log_rolled_back_by', 'user', ['rolled_back_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_log_rolled_back_by', type_='foreignkey')
        batch_op.drop_column('rolled_back_at')
        batch_op.drop_column('rolled_back_by')
        batch_op.drop_column('rolled_back')
        batch_op.drop_column('new_data')
        batch_op.drop_column('old_data')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_model')
        batch_op.drop_column('rollback_type')
        batch_op.drop_column('can_rollback')

    # ### end Alembic commands ###
