"""update_sales_order_item_specs_to_string_fields

Revision ID: 7dc0131be17e
Revises: 011e395c1aa4
Create Date: 2025-06-04 13:36:43.556727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc0131be17e'
down_revision = '011e395c1aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('spec_extended',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('spec_gasket',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('spec_joint',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('spec_drilling',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('spec_other',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_unique_constraint('uq_sales_order_item_global_sn', ['global_sn'])

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_sales_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_unique_constraint('uq_sales_order_global_sn', ['global_sn'])
        batch_op.create_unique_constraint('uq_sales_order_number', ['order_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_sales_order_number', type_='unique')
        batch_op.drop_constraint('uq_sales_order_global_sn', type_='unique')
        batch_op.drop_index(batch_op.f('ix_sales_orders_order_number'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_sales_order_item_global_sn', type_='unique')
        batch_op.alter_column('spec_other',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('spec_drilling',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('spec_joint',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('spec_gasket',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('spec_extended',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
