"""add production batch association to task assignment

Revision ID: 7fb3e057c2d2
Revises: 005f0adfdd4d
Create Date: 2025-05-30 02:27:37.486451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb3e057c2d2'
down_revision = '005f0adfdd4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_batch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('batch_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('task_type', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_task_assignment_production_batch_id', 'production_batches', ['production_batch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_task_assignment_batch_item_id', 'production_batch_items', ['batch_item_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_assignment_batch_item_id', type_='foreignkey')
        batch_op.drop_constraint('fk_task_assignment_production_batch_id', type_='foreignkey')
        batch_op.drop_column('task_type')
        batch_op.drop_column('batch_item_id')
        batch_op.drop_column('production_batch_id')

    # ### end Alembic commands ###
