"""add has_output and needs_inspection to process_price

Revision ID: 81d69499eb59
Revises: f605d7860467
Create Date: 2025-05-12 14:39:15.072188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d69499eb59'
down_revision = 'f605d7860467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_output', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('needs_inspection', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_price', schema=None) as batch_op:
        batch_op.drop_column('needs_inspection')
        batch_op.drop_column('has_output')

    # ### end Alembic commands ###
