"""add_specification_fields_to_sales_order_items

Revision ID: 83bfde43921e
Revises: f4ff7bdd25b0
Create Date: 2025-05-31 00:18:40.775426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83bfde43921e'
down_revision = 'f4ff7bdd25b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_delivery_batches', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_delivery_batch_global_sn', ['global_sn'])

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spec_other', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_sales_order_item_global_sn', ['global_sn'])

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_sales_order_global_sn', ['global_sn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sales_order_global_sn', type_='unique')

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sales_order_item_global_sn', type_='unique')
        batch_op.drop_column('spec_other')

    with op.batch_alter_table('sales_order_delivery_batches', schema=None) as batch_op:
        batch_op.drop_constraint('uq_delivery_batch_global_sn', type_='unique')

    # ### end Alembic commands ###
