"""add serial number to all tables

Revision ID: 9b4e4b994b15
Revises: 0ca44244cca0
Create Date: 2025-03-27 12:24:17.673564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '9b4e4b994b15'
down_revision = '0ca44244cca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    
    # 删除可能存在的临时表
    temp_tables = [
        '_alembic_tmp_bonus_penalty',
        '_alembic_tmp_employee',
        '_alembic_tmp_process_price',
        '_alembic_tmp_production_record',
        '_alembic_tmp_task_assignment'
    ]
    for table in temp_tables:
        try:
            conn.execute(f"DROP TABLE IF EXISTS {table}")
        except:
            pass
    
    if 'serial_numbers' not in tables:
        op.create_table('serial_numbers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('current_number', sa.Integer(), nullable=False),
        sa.Column('last_updated', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        # 插入初始记录
        conn.execute(
            "INSERT INTO serial_numbers (id, current_number, last_updated) VALUES (1, 0, ?)",
            [datetime.now()]
        )
    
    # 为每个表添加serial_number列，并设置默认值
    tables_to_update = [
        ('bonus_penalty', 'uq_bonus_penalty_serial_number'),
        ('employee', 'uq_employee_serial_number'),
        ('process_price', 'uq_process_price_serial_number'),
        ('production_record', 'uq_production_record_serial_number'),
        ('task_assignment', 'uq_task_assignment_serial_number')
    ]
    
    for table_name, constraint_name in tables_to_update:
        # 检查列是否存在
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        if 'serial_number' not in columns:
            # 添加serial_number列，但允许为空
            with op.batch_alter_table(table_name, schema=None) as batch_op:
                batch_op.add_column(sa.Column('serial_number', sa.String(length=8), nullable=True))
            
            # 获取当前最大序号
            result = conn.execute("SELECT current_number FROM serial_numbers WHERE id = 1").fetchone()
            current_number = result[0] if result else 0
            
            # 更新现有记录的serial_number
            records = conn.execute(f"SELECT id FROM {table_name}").fetchall()
            for record in records:
                current_number += 1
                serial_number = f"{current_number:08d}"
                conn.execute(
                    f"UPDATE {table_name} SET serial_number = ? WHERE id = ?",
                    [serial_number, record[0]]
                )
            
            # 更新serial_numbers表中的current_number
            conn.execute(
                "UPDATE serial_numbers SET current_number = ?, last_updated = ? WHERE id = 1",
                [current_number, datetime.now()]
            )
            
            # 设置serial_number列为非空并添加唯一约束
            with op.batch_alter_table(table_name, schema=None) as batch_op:
                batch_op.alter_column('serial_number', nullable=False)
                batch_op.create_unique_constraint(constraint_name, ['serial_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_task_assignment_serial_number', type_='unique')
        batch_op.drop_column('serial_number')

    with op.batch_alter_table('production_record', schema=None) as batch_op:
        batch_op.drop_constraint('uq_production_record_serial_number', type_='unique')
        batch_op.drop_column('serial_number')

    with op.batch_alter_table('process_price', schema=None) as batch_op:
        batch_op.drop_constraint('uq_process_price_serial_number', type_='unique')
        batch_op.drop_column('serial_number')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_serial_number', type_='unique')
        batch_op.drop_column('serial_number')

    with op.batch_alter_table('bonus_penalty', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bonus_penalty_serial_number', type_='unique')
        batch_op.drop_column('serial_number')

    op.drop_table('serial_numbers')
    # ### end Alembic commands ###
