"""Add specifications and direction to TaskAssignment

Revision ID: 9ee35212d2fe
Revises: 7dc0131be17e
Create Date: 2025-06-06 04:10:43.963450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee35212d2fe'
down_revision = '7dc0131be17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spec_extended', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spec_gasket', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spec_joint', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spec_drilling', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spec_other', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spec_other_desc', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('direction', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.drop_column('direction')
        batch_op.drop_column('spec_other_desc')
        batch_op.drop_column('spec_other')
        batch_op.drop_column('spec_drilling')
        batch_op.drop_column('spec_joint')
        batch_op.drop_column('spec_gasket')
        batch_op.drop_column('spec_extended')

    # ### end Alembic commands ###
