"""Update raw_material model: remove material_name, require category_id

Revision ID: 9f02bbbbd492
Revises: c4b4caaebd94
Create Date: 2025-06-11 17:06:04.807916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9f02bbbbd492'
down_revision = 'c4b4caaebd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_notification_rules')
    op.drop_table('sqlite_sequence')
    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_notification_rule_global_sn', ['global_sn'])

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_notification_template_code', ['template_code'])
        batch_op.create_unique_constraint('uq_notification_template_global_sn', ['global_sn'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_notification_global_sn', ['global_sn'])

    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sales_orders', ['sales_order_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'sales_order_items', ['sales_order_item_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'raw_material_categories', ['category_id'], ['id'])
        batch_op.drop_column('material_name')

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_column('usage_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_unit', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notification_global_sn', type_='unique')

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notification_template_global_sn', type_='unique')
        batch_op.drop_constraint('uq_notification_template_code', type_='unique')

    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notification_rule_global_sn', type_='unique')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.create_table('_alembic_tmp_notification_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('global_sn', sa.VARCHAR(length=8), nullable=False),
    sa.Column('rule_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('trigger_conditions', sqlite.JSON(), nullable=True),
    sa.Column('receiver_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('receiver_config', sqlite.JSON(), nullable=True),
    sa.Column('notification_methods', sqlite.JSON(), nullable=True),
    sa.Column('template_config', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn', name='uq_notification_rule_global_sn')
    )
    # ### end Alembic commands ###
