"""Add sales order management tables

Revision ID: a3f28e475446
Revises: 166a7ce7b905
Create Date: 2025-05-30 22:10:52.918177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f28e475446'
down_revision = '166a7ce7b905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('order_source', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_year', sa.Integer(), nullable=False),
    sa.Column('order_month', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_sales_order_global_sn'),
    sa.UniqueConstraint('order_number', name='uq_sales_order_number')
    )
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_orders_order_number'), ['order_number'], unique=True)

    op.create_table('sales_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('drawing_number', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('specification_type', sa.String(length=20), nullable=False),
    sa.Column('specification_detail', sa.String(length=200), nullable=True),
    sa.Column('usage_unit', sa.String(length=50), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=False),
    sa.Column('delivery_time', sa.DateTime(), nullable=False),
    sa.Column('delivery_station_notes', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_sales_order_item_global_sn')
    )
    op.create_table('sales_order_delivery_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('planned_delivery_time', sa.DateTime(), nullable=False),
    sa.Column('actual_delivery_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['sales_order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_delivery_batch_global_sn'),
    sa.UniqueConstraint('order_item_id', 'batch_number', name='uq_delivery_batch_number')
    )
    with op.batch_alter_table('customer_addresses', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_customer_address_global_sn', ['global_sn'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_customer_global_sn', ['global_sn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customer_global_sn', type_='unique')

    with op.batch_alter_table('customer_addresses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customer_address_global_sn', type_='unique')

    op.drop_table('sales_order_delivery_batches')
    op.drop_table('sales_order_items')
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_orders_order_number'))

    op.drop_table('sales_orders')
    # ### end Alembic commands ###
