"""Add notes field to InspectionTask

Revision ID: aa8736ba6969
Revises: f63ce20582f8
Create Date: 2025-05-28 03:58:58.191505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8736ba6969'
down_revision = 'f63ce20582f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_records_template_id'), ['template_id'], unique=False)

    with op.batch_alter_table('inspection_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True, comment='备注说明'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_tasks', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_records_template_id'))

    # ### end Alembic commands ###
