"""initial migration

Revision ID: b8a234ed213f
Revises: 
Create Date: 2025-04-29 16:40:13.039155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a234ed213f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('serial_number', sa.String(length=8), nullable=False),
    sa.Column('product_number', sa.String(length=50), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('drawing_number', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('inspector', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_finished_product_global_sn'),
    sa.UniqueConstraint('serial_number'),
    sa.UniqueConstraint('serial_number', name='uq_finished_product_serial_number')
    )
    with op.batch_alter_table('finished_product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finished_product_product_number'), ['product_number'], unique=False)

    op.create_table('process_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('process_code', sa.String(length=50), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('drawing_no', sa.String(length=100), nullable=True),
    sa.Column('model_no', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('price_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_process_price_global_sn')
    )
    with op.batch_alter_table('process_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_price_process_code'), ['process_code'], unique=False)

    op.create_table('raw_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=False),
    sa.Column('material_name', sa.String(length=100), nullable=False),
    sa.Column('melt_number', sa.String(length=100), nullable=False),
    sa.Column('supplier_number', sa.String(length=100), nullable=False),
    sa.Column('has_sample', sa.Boolean(), nullable=True),
    sa.Column('storage_date', sa.DateTime(), nullable=False),
    sa.Column('internal_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_raw_material_global_sn'),
    sa.UniqueConstraint('internal_number', name='uq_raw_material_internal_number')
    )
    op.create_table('serial_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('can_rollback', sa.Boolean(), nullable=True),
    sa.Column('rollback_type', sa.String(length=50), nullable=True),
    sa.Column('target_model', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('rolled_back', sa.Boolean(), nullable=True),
    sa.Column('rolled_back_by', sa.Integer(), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rolled_back_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_employee_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_employee_global_sn')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_employee_id'), ['employee_id'], unique=True)

    op.create_table('process_price_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('subtotal_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['process_price.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtotal_id'], ['process_price.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_process_price_group_global_sn'),
    sa.UniqueConstraint('subtotal_id', 'process_id', name='uq_subtotal_process')
    )
    op.create_table('bonus_penalty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_price.id'], name='fk_bp_process_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_bonus_penalty_global_sn')
    )
    op.create_table('employee_coefficient_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('old_coefficient', sa.Float(), nullable=False),
    sa.Column('new_coefficient', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_coefficient_history_creator_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_coefficient_history_employee_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_coefficient_history_global_sn')
    )
    op.create_table('employee_salary_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('old_salary', sa.Float(), nullable=False),
    sa.Column('new_salary', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_salary_history_creator_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_salary_history_employee_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_salary_history_global_sn')
    )
    op.create_table('production_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_price.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_production_record_global_sn')
    )
    op.create_table('task_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('completed_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_price.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_task_assignment_global_sn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_assignment')
    op.drop_table('production_record')
    op.drop_table('employee_salary_history')
    op.drop_table('employee_coefficient_history')
    op.drop_table('bonus_penalty')
    op.drop_table('process_price_group')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_employee_id'))

    op.drop_table('employee')
    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('serial_numbers')
    op.drop_table('raw_material')
    with op.batch_alter_table('process_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_price_process_code'))

    op.drop_table('process_price')
    with op.batch_alter_table('finished_product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finished_product_product_number'))

    op.drop_table('finished_product')
    # ### end Alembic commands ###
