"""add_production_record_materials_relationship

Revision ID: bcb9bf714586
Revises: 142d11630569
Create Date: 2025-05-12 18:22:39.910099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb9bf714586'
down_revision = '142d11630569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('change_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['raw_material.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_inventory_change_global_sn')
    )
    op.create_table('production_record_materials',
    sa.Column('production_record_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['production_record_id'], ['production_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('production_record_id', 'raw_material_id')
    )
    with op.batch_alter_table('production_record', schema=None) as batch_op:
        batch_op.drop_constraint('fk_production_record_raw_material', type_='foreignkey')
        batch_op.drop_column('raw_material_id')
        batch_op.drop_column('raw_material_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_material_quantity', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('raw_material_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_production_record_raw_material', 'raw_material', ['raw_material_id'], ['id'])

    op.drop_table('production_record_materials')
    op.drop_table('inventory_change')
    # ### end Alembic commands ###
