"""add quality management tables

Revision ID: c02604883c72
Revises: 
Create Date: 2025-05-14 14:40:16.101212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02604883c72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('serial_number', sa.String(length=8), nullable=False),
    sa.Column('product_number', sa.String(length=50), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('drawing_number', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('inspector', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_finished_product_global_sn'),
    sa.UniqueConstraint('serial_number'),
    sa.UniqueConstraint('serial_number', name='uq_finished_product_serial_number')
    )
    with op.batch_alter_table('finished_product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finished_product_product_number'), ['product_number'], unique=False)

    op.create_table('raw_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=False),
    sa.Column('material_name', sa.String(length=100), nullable=False),
    sa.Column('melt_number', sa.String(length=100), nullable=False),
    sa.Column('supplier_number', sa.String(length=100), nullable=False),
    sa.Column('has_sample', sa.Boolean(), nullable=True),
    sa.Column('storage_date', sa.DateTime(), nullable=False),
    sa.Column('internal_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_raw_material_global_sn'),
    sa.UniqueConstraint('internal_number', name='uq_raw_material_internal_number')
    )
    op.create_table('serial_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('can_rollback', sa.Boolean(), nullable=True),
    sa.Column('rollback_type', sa.String(length=50), nullable=True),
    sa.Column('target_model', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('rolled_back', sa.Boolean(), nullable=True),
    sa.Column('rolled_back_by', sa.Integer(), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rolled_back_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code_type', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=True),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('sequence_length', sa.Integer(), nullable=False),
    sa.Column('current_sequence', sa.Integer(), nullable=True),
    sa.Column('reset_frequency', sa.String(length=20), nullable=True),
    sa.Column('last_reset_date', sa.DateTime(), nullable=True),
    sa.Column('format_pattern', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_employee_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_employee_global_sn')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_employee_id'), ['employee_id'], unique=True)

    op.create_table('inspection_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_code', sa.String(length=50), nullable=False, comment='模板编码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='模板类型(product/process/material)'),
    sa.Column('description', sa.Text(), nullable=True, comment='模板描述'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_code')
    )
    op.create_table('code_generation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('generated_code', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['code_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_coefficient_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('old_coefficient', sa.Float(), nullable=False),
    sa.Column('new_coefficient', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_coefficient_history_creator_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_coefficient_history_employee_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_coefficient_history_global_sn')
    )
    op.create_table('employee_salary_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('old_salary', sa.Float(), nullable=False),
    sa.Column('new_salary', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_salary_history_creator_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_salary_history_employee_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_salary_history_global_sn')
    )
    op.create_table('inspection_base_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='信息项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('notes', sa.Text(), nullable=True, comment='项目备注'),
    sa.Column('input_type', sa.String(length=20), nullable=False, comment='输入类型(text/number/date/select)'),
    sa.Column('default_value', sa.String(length=200), nullable=True, comment='默认值'),
    sa.Column('options', sa.JSON(), nullable=True, comment='选择项(JSON格式)'),
    sa.Column('is_required', sa.Boolean(), nullable=True, comment='是否必填'),
    sa.Column('validation_rules', sa.JSON(), nullable=True, comment='验证规则(JSON格式)'),
    sa.Column('order_num', sa.Integer(), nullable=True, comment='排序号'),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=50), nullable=False, comment='全局流水号'),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False, comment='检验对象类型(product/process/material)'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='检验对象ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='任务状态(pending/in_progress/completed/cancelled)'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='优先级'),
    sa.Column('deadline', sa.DateTime(), nullable=True, comment='截止时间'),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn')
    )
    op.create_table('process_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('process_code', sa.String(length=50), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('drawing_no', sa.String(length=100), nullable=True),
    sa.Column('model_no', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('price_type', sa.String(length=20), nullable=False),
    sa.Column('has_output', sa.Boolean(), nullable=True),
    sa.Column('output_type', sa.String(length=20), nullable=True),
    sa.Column('code_rule_id', sa.Integer(), nullable=True),
    sa.Column('needs_inspection', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['code_rule_id'], ['code_rule.id'], name='fk_process_code_rule_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_process_price_global_sn')
    )
    with op.batch_alter_table('process_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_price_process_code'), ['process_code'], unique=False)

    op.create_table('bonus_penalty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_price.id'], name='fk_bp_process_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_bonus_penalty_global_sn')
    )
    op.create_table('inspection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='检验项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('notes', sa.Text(), nullable=True, comment='项目备注'),
    sa.Column('inspection_method', sa.Text(), nullable=True, comment='检验方法'),
    sa.Column('standard', sa.Text(), nullable=True, comment='检验标准'),
    sa.Column('standard_value', sa.Float(), nullable=True, comment='标准值'),
    sa.Column('linked_base_item_id', sa.Integer(), nullable=True, comment='关联的基本信息项目ID'),
    sa.Column('use_linked_value', sa.Boolean(), nullable=True, comment='是否使用关联值作为标准值'),
    sa.Column('value_extraction_rule', sa.JSON(), nullable=True, comment='值提取规则(JSON格式)'),
    sa.Column('deviation_type', sa.String(length=20), nullable=True, comment='偏差类型(value/percentage)'),
    sa.Column('upper_deviation_value', sa.Float(), nullable=True, comment='上偏差值'),
    sa.Column('lower_deviation_value', sa.Float(), nullable=True, comment='下偏差值'),
    sa.Column('upper_deviation_percentage', sa.Float(), nullable=True, comment='上偏差百分比'),
    sa.Column('lower_deviation_percentage', sa.Float(), nullable=True, comment='下偏差百分比'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('order_num', sa.Integer(), nullable=True, comment='排序号'),
    sa.ForeignKeyConstraint(['linked_base_item_id'], ['inspection_base_items.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=50), nullable=False, comment='全局流水号'),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False, comment='检验日期'),
    sa.Column('result', sa.String(length=20), nullable=False, comment='总体检验结果(pass/fail)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注说明'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['inspection_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('process_price_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('subtotal_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['process_price.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtotal_id'], ['process_price.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_process_price_group_global_sn'),
    sa.UniqueConstraint('subtotal_id', 'process_id', name='uq_subtotal_process')
    )
    op.create_table('production_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_material_id', sa.Integer(), nullable=True),
    sa.Column('raw_material_quantity', sa.Float(), nullable=True),
    sa.Column('finished_product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['finished_product_id'], ['finished_product.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_price.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn')
    )
    op.create_table('task_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('completed_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_price.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_task_assignment_global_sn')
    )
    op.create_table('inspection_base_item_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('base_item_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False, comment='记录的值'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注说明'),
    sa.ForeignKeyConstraint(['base_item_id'], ['inspection_base_items.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['inspection_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_item_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('measured_value', sa.Float(), nullable=False, comment='实测值'),
    sa.Column('is_qualified', sa.Boolean(), nullable=False, comment='是否合格'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注说明'),
    sa.Column('evidence', sa.String(length=500), nullable=True, comment='证据(如照片路径)'),
    sa.ForeignKeyConstraint(['item_id'], ['inspection_items.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['inspection_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nonconformity_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False, comment='处理类型(rework/scrap/accept)'),
    sa.Column('handler_id', sa.Integer(), nullable=False),
    sa.Column('handling_date', sa.Date(), nullable=False, comment='处理日期'),
    sa.Column('handling_result', sa.Text(), nullable=False, comment='处理结果'),
    sa.Column('notes', sa.Text(), nullable=True, comment='处理说明'),
    sa.ForeignKeyConstraint(['handler_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['inspection_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_record_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_record_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['production_record_id'], ['production_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_record_materials')
    op.drop_table('nonconformity_records')
    op.drop_table('inspection_item_records')
    op.drop_table('inspection_base_item_records')
    op.drop_table('task_assignment')
    op.drop_table('production_record')
    op.drop_table('process_price_group')
    op.drop_table('inspection_records')
    op.drop_table('inspection_items')
    op.drop_table('bonus_penalty')
    with op.batch_alter_table('process_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_price_process_code'))

    op.drop_table('process_price')
    op.drop_table('inspection_tasks')
    op.drop_table('inspection_base_items')
    op.drop_table('employee_salary_history')
    op.drop_table('employee_coefficient_history')
    op.drop_table('code_generation_log')
    op.drop_table('inspection_templates')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_employee_id'))

    op.drop_table('employee')
    op.drop_table('code_rule')
    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('serial_numbers')
    op.drop_table('raw_material')
    with op.batch_alter_table('finished_product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finished_product_product_number'))

    op.drop_table('finished_product')
    # ### end Alembic commands ###
