"""Remove material_name from raw_material, make category_id required

Revision ID: c117632ece3d
Revises: c4b4caaebd94
Create Date: 2025-06-11 16:39:25.825439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c117632ece3d'
down_revision = 'c4b4caaebd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_notification_rule_global_sn', ['global_sn'])

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_notification_template_code', ['template_code'])
        batch_op.create_unique_constraint('uq_notification_template_global_sn', ['global_sn'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_notification_global_sn', ['global_sn'])

    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sales_orders', ['sales_order_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'sales_order_items', ['sales_order_item_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'raw_material_categories', ['category_id'], ['id'])
        batch_op.drop_column('material_name')

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_column('usage_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_unit', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notification_global_sn', type_='unique')

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notification_template_global_sn', type_='unique')
        batch_op.drop_constraint('uq_notification_template_code', type_='unique')

    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notification_rule_global_sn', type_='unique')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
