"""add_notification_system

Revision ID: c4863dae8be6
Revises: c81522b131f7
Create Date: 2025-06-06 04:45:45.969537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4863dae8be6'
down_revision = 'c81522b131f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_conditions', sa.JSON(), nullable=True),
    sa.Column('receiver_type', sa.String(length=20), nullable=False),
    sa.Column('receiver_config', sa.JSON(), nullable=True),
    sa.Column('notification_methods', sa.JSON(), nullable=True),
    sa.Column('template_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_notification_rule_global_sn')
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('title_template', sa.String(length=200), nullable=False),
    sa.Column('content_template', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('notification_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_notification_template_global_sn'),
    sa.UniqueConstraint('template_code'),
    sa.UniqueConstraint('template_code', name='uq_notification_template_code')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sn', sa.String(length=8), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_data', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('related_model', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['notification_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_sn'),
    sa.UniqueConstraint('global_sn', name='uq_notification_global_sn')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notification_created', ['created_at'], unique=False)
        batch_op.create_index('ix_notification_status', ['status'], unique=False)
        batch_op.create_index('ix_notification_type', ['trigger_type'], unique=False)

    op.create_table('notification_receivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_method', sa.String(length=20), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=True),
    sa.Column('delivery_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'user_id', name='uq_notification_receiver')
    )
    with op.batch_alter_table('notification_receivers', schema=None) as batch_op:
        batch_op.create_index('ix_receiver_status', ['status'], unique=False)
        batch_op.create_index('ix_receiver_user_status', ['user_id', 'status'], unique=False)

    # 注释掉系统表操作避免错误
    # op.drop_table('sqlite_sequence')
    
    # 生产订单外键已存在，跳过
    # with op.batch_alter_table('production_orders', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'sales_order_items', ['sales_order_item_id'], ['id'], ondelete='SET NULL')
    #     batch_op.create_foreign_key(None, 'sales_orders', ['sales_order_id'], ['id'], ondelete='SET NULL')

    # usage_unit字段已删除，跳过
    # with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
    #     batch_op.drop_column('usage_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 注释掉系统表和已存在字段的操作
    # with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('usage_unit', sa.VARCHAR(length=100), nullable=True))

    # with op.batch_alter_table('production_orders', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')

    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    with op.batch_alter_table('notification_receivers', schema=None) as batch_op:
        batch_op.drop_index('ix_receiver_user_status')
        batch_op.drop_index('ix_receiver_status')

    op.drop_table('notification_receivers')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_type')
        batch_op.drop_index('ix_notification_status')
        batch_op.drop_index('ix_notification_created')

    op.drop_table('notifications')
    op.drop_table('notification_templates')
    op.drop_table('notification_rules')
    # ### end Alembic commands ###
