"""Add raw material categories table

Revision ID: c4b4caaebd94
Revises: c4863dae8be6
Create Date: 2025-06-11 15:54:17.232841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b4caaebd94'
down_revision = 'c4863dae8be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_material_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_notification_rule_global_sn', ['global_sn'])

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_notification_template_code', ['template_code'])
        batch_op.create_unique_constraint('uq_notification_template_global_sn', ['global_sn'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_notification_global_sn', ['global_sn'])

    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sales_order_items', ['sales_order_item_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'sales_orders', ['sales_order_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'raw_material_categories', ['category_id'], ['id'])

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_column('usage_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_unit', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notification_global_sn', type_='unique')

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notification_template_global_sn', type_='unique')
        batch_op.drop_constraint('uq_notification_template_code', type_='unique')

    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notification_rule_global_sn', type_='unique')

    op.drop_table('raw_material_categories')
    # ### end Alembic commands ###
