"""add_specs_to_production_batch

Revision ID: c81522b131f7
Revises: 9ee35212d2fe
Create Date: 2025-06-06 04:30:47.895488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81522b131f7'
down_revision = '9ee35212d2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 为 production_batches 表添加规格型号字段
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spec_extended', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spec_gasket', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spec_joint', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spec_drilling', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spec_other', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spec_other_desc', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('direction', sa.String(length=50), nullable=True))
    
    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sales_order_items', ['sales_order_item_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'sales_orders', ['sales_order_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_column('usage_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_unit', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # 移除 production_batches 表的规格型号字段
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.drop_column('direction')
        batch_op.drop_column('spec_other_desc')
        batch_op.drop_column('spec_other')
        batch_op.drop_column('spec_drilling')
        batch_op.drop_column('spec_joint')
        batch_op.drop_column('spec_gasket')
        batch_op.drop_column('spec_extended')
    # ### end Alembic commands ###
