"""Add employee salary and coefficient history tables

Revision ID: d63a1e23c848
Revises: 9b4e4b994b15
Create Date: 2025-04-01 11:17:06.091400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63a1e23c848'
down_revision = '9b4e4b994b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonus_penalty', schema=None) as batch_op:
        batch_op.alter_column('serial_number',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.create_unique_constraint('uq_bonus_penalty_serial_number', ['serial_number'])

    with op.batch_alter_table('employee_coefficient_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=8), nullable=False))
        batch_op.create_unique_constraint('uq_coefficient_history_serial_number', ['serial_number'])

    with op.batch_alter_table('employee_salary_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=8), nullable=False))
        batch_op.create_unique_constraint('uq_salary_history_serial_number', ['serial_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_salary_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_salary_history_serial_number', type_='unique')
        batch_op.drop_column('serial_number')

    with op.batch_alter_table('employee_coefficient_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_coefficient_history_serial_number', type_='unique')
        batch_op.drop_column('serial_number')

    with op.batch_alter_table('bonus_penalty', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bonus_penalty_serial_number', type_='unique')
        batch_op.alter_column('serial_number',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)

    # ### end Alembic commands ###
