"""add code rule and generation log tables

Revision ID: f605d7860467
Revises: b8a234ed213f
Create Date: 2025-04-29 16:55:12.073658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f605d7860467'
down_revision = 'b8a234ed213f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code_type', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=True),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('sequence_length', sa.Integer(), nullable=False),
    sa.Column('current_sequence', sa.Integer(), nullable=True),
    sa.Column('reset_frequency', sa.String(length=20), nullable=True),
    sa.Column('last_reset_date', sa.DateTime(), nullable=True),
    sa.Column('format_pattern', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('code_generation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('generated_code', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['code_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bonus_penalty', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_bonus_penalty_global_sn', ['global_sn'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_employee_global_sn', ['global_sn'])

    with op.batch_alter_table('employee_coefficient_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_coefficient_history_global_sn', ['global_sn'])

    with op.batch_alter_table('employee_salary_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_salary_history_global_sn', ['global_sn'])

    with op.batch_alter_table('finished_product', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_finished_product_global_sn', ['global_sn'])
        batch_op.create_unique_constraint('uq_finished_product_serial_number', ['serial_number'])

    with op.batch_alter_table('process_price', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_process_price_global_sn', ['global_sn'])

    with op.batch_alter_table('process_price_group', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_process_price_group_global_sn', ['global_sn'])

    with op.batch_alter_table('production_record', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_production_record_global_sn', ['global_sn'])

    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_raw_material_global_sn', ['global_sn'])

    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_task_assignment_global_sn', ['global_sn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_task_assignment_global_sn', type_='unique')

    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.drop_constraint('uq_raw_material_global_sn', type_='unique')

    with op.batch_alter_table('production_record', schema=None) as batch_op:
        batch_op.drop_constraint('uq_production_record_global_sn', type_='unique')

    with op.batch_alter_table('process_price_group', schema=None) as batch_op:
        batch_op.drop_constraint('uq_process_price_group_global_sn', type_='unique')

    with op.batch_alter_table('process_price', schema=None) as batch_op:
        batch_op.drop_constraint('uq_process_price_global_sn', type_='unique')

    with op.batch_alter_table('finished_product', schema=None) as batch_op:
        batch_op.drop_constraint('uq_finished_product_serial_number', type_='unique')
        batch_op.drop_constraint('uq_finished_product_global_sn', type_='unique')

    with op.batch_alter_table('employee_salary_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_salary_history_global_sn', type_='unique')

    with op.batch_alter_table('employee_coefficient_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_coefficient_history_global_sn', type_='unique')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_global_sn', type_='unique')

    with op.batch_alter_table('bonus_penalty', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bonus_penalty_global_sn', type_='unique')

    op.drop_table('code_generation_log')
    op.drop_table('code_rule')
    # ### end Alembic commands ###
